"""empty message

Revision ID: b53458cc2c56
Revises: c4799404114b
Create Date: 2016-05-03 12:28:16.760061

"""

# revision identifiers, used by Alembic.
revision = 'b53458cc2c56'
down_revision = 'c4799404114b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    ### end Alembic commands ###
