"""empty message

Revision ID: c4799404114b
Revises: None
Create Date: 2016-04-26 15:27:21.118662

"""

# revision identifiers, used by Alembic.
revision = 'c4799404114b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_of_things',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('assembled', sa.Boolean(), nullable=True),
    sa.Column('marketable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_supplier'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('things',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('price', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measures.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types_of_things.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('consist_of',
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8.3), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['things.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['things.id'], ),
    sa.PrimaryKeyConstraint('thing_id', 'part_id')
    )
    op.create_table('invoices',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('price', sa.Numeric(precision=8.3), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['things.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'thing_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('assembly_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['things.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('timelimit', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_assembler',
    sa.Column('assembler_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assembler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_assembler')
    op.drop_table('tasks')
    op.drop_table('products')
    op.drop_table('invoices')
    op.drop_table('consist_of')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('things')
    op.drop_table('shipments')
    op.drop_table('types_of_things')
    op.drop_table('suppliers')
    op.drop_table('measures')
    op.drop_table('groups')
    ### end Alembic commands ###
